#tag::oauth2[]
micronaut:
  security:
    oauth2:
      clients:
        github: # <1>
          client-id:  '${OAUTH_CLIENT_ID}' # <2>
          client-secret: '${OAUTH_CLIENT_SECRET}' # <3>
          scopes: # <4>
            - user:email
            - read:user
            - public_repo
          authorization:
            url: 'https://github.com/login/oauth/authorize' # <5>
          token:
            url: 'https://github.com/login/oauth/access_token' # <6>
            auth-method: client-secret-post
    token:
      jwt:
        cookie:
          enabled: true # <7>
    endpoints:
      logout:
        enabled: true  # <8>
        get-allowed: true # <9>
#end::oauth2[]
---
micronaut:
  application:
    name: complete
---
#tag::micronaut-http-services[]
micronaut:
  http:
    services:
      githubv3:
        url: "https://api.github.com"
#end::micronaut-http-services[]