micronaut:
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        cookie:
          enabled: true
    endpoints:
      logout:
        enabled: true
        get-allowed: true
    oauth2:
      enabled: true
      clients:
        github:
          client-id:  '${OAUTH_CLIENT_ID}'
          client-secret: '${OAUTH_CLIENT_SECRET}'
          scopes:
            - user:email
            - read:user
            - public_repo
          authorization:
            url: https://github.com/login/oauth/authorize
          token:
            url: https://github.com/login/oauth/access_token
            auth-method: client-secret-post
  application:
    name: complete
